export const FIELD_OPTIONS = [
  {
    id: 'web-development',
    label: 'Web development',
    topics: [
      'Frontend',
      'Backend',
      'Fullstack',
      'Database',
      'API & integration',
      'DevOps & deployment',
      'Testing',
      'State management',
      'Build tools & bundlers',
      'Package managers',
      'Security',
      'CMS(content management)',
      'Analytics & monitoring',
    ],
  },
  {
    id: 'ai',
    label: 'AI',
    topics: [
      'Data Processing & ETL',
      'Machine Learning (ML)',
      'Deep Learning',
      'Natural Language Processing (NLP)',
      'Computer Vision (CV)',
      'Reinforcement Learning',
      'MLOps & Deployment',
      'AutoML',
      'Generative AI',
      'Prompt Engineering',
      'Model Optimization',
      'Data Labeling',
      'Explainable AI (XAI)',
    ],
  },
  {
    id: 'game-development',
    label: 'Game development',
    topics: [
      'Game Engines',
      '2D Game Development',
      '3D Game Development',
      'Game Design & Prototyping',
      'Physics & Simulation',
      'Animation & Rigging',
      'Shaders & Visual Effects (VFX)',
      'Audio & Sound Design',
      'Game AI',
      'Multiplayer & Networking',
      'Game Optimization',
      'Version Control for Games',
      'Mobile Game Development',
      'Game Testing & QA',
      'Game Monetization',
    ],
  },
  {
    id: 'blockchain',
    label: 'Blockchain',
    topics: [
      'Smart Contract Development',
      'Blockchain Platforms',
      'Frameworks & Tools',
      'Web3 Libraries',
      'Wallets & Authentication',
      'DeFi (Decentralized Finance)',
      'NFTs (Non-Fungible Tokens)',
      'Layer 2 & Scaling',
      'Oracles',
      'Indexing & Query',
      'Security & Auditing',
      'Node Infrastructure',
      'Stablecoins',
      'DAOs (Decentralized Autonomous Orgs)',
      'Cryptography',
    ],
  },
  {
    id: 'architecture',
    label: 'Architecture',
    topics: [
      '2D Drafting & Documentation',
      '3D Modeling & Visualization',
      'BIM (Building Information Modeling)',
      'Rendering & Visualization',
      'Structural Analysis',
      'Environmental Simulation',
      'Construction Management',
      'Urban Planning & GIS',
      'Landscape Architecture',
      'Interior Architecture',
      'Computational Design',
      'Site Analysis & Surveying',
      'Project Documentation',
      'Code Compliance',
      'Virtual Reality (Archviz VR)',
    ],
  },
  {
    id: 'art',
    label: 'Art',
    topics: [
      'Digital Painting & Illustration',
      'Vector Art & Graphics',
      'Concept Art',
      'Traditional Art (Digital Simulation)',
      'Pixel Art',
      '3D Sculpting & Modeling',
      'Texture & Material Creation',
      'Digital Collage & Mixed Media',
      'Typography',
      'Color Theory Tools',
      'Composition & Perspective Tools',
      'Art Management & Portfolio',
      'Printmaking (Digital)',
      'Animation (2D Hand-drawn)',
      'Generative Art',
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    topics: [
      'Digital Marketing',
      'Search Engine Optimization (SEO)',
      'Content Marketing',
      'Email Marketing',
      'Social Media Management',
      'Marketing Analytics',
      'Customer Relationship Management (CRM)',
      'Marketing Automation',
      'Influencer Marketing',
      'Affiliate Marketing',
      'Landing Page Builders',
      'A/B Testing & Optimization',
      'Customer Feedback & Surveys',
      'Public Relations (PR)',
      'Brand Strategy Tools',
      'Marketing Project Management',
      'Video Marketing',
      'SMS Marketing',
      'E-commerce Marketing',
      'Community Marketing',
    ],
  },
  {
    id: 'multimedia',
    label: 'Multimedia',
    topics: [
      'Video Editing',
      'Motion Graphics & VFX',
      '3D Animation',
      'Audio Editing & Mixing',
      'Sound Design',
      'Music Production',
      'Podcasting',
      'Visual Effects (VFX)',
      'Color Grading',
      'Screen Recording & Tutorials',
      'Broadcasting & Streaming',
      'Interactive Multimedia',
      'Virtual Reality (VR) Multimedia',
      'Augmented Reality (AR)',
      '3D Scanning & Photogrammetry',
      'Digital Signage',
      'Subtitling & Captioning',
      'Compression & Encoding',
      'Stock Media (for practice)',
      'Thumbnail & YouTube Graphics',
    ],
  },
  {
    id: 'mobile-development',
    label: 'Mobile development',
    topics: [
      'Native Android',
      'Native iOS',
      'Cross-Platform (Framework)',
      'Mobile UI/UX Design',
      'Mobile Backend & APIs',
      'Mobile Databases',
      'Mobile State Management',
      'Mobile Testing',
      'Mobile CI/CD',
      'Mobile Analytics & Crash Reporting',
      'Mobile Push Notifications',
      'Mobile Payments & Subscriptions',
      'Mobile App Distribution',
      'Mobile Performance Optimization',
      'Mobile Security',
    ],
  },
  {
    id: 'desktop-applications',
    label: 'Desktop applications',
    topics: [
      'Cross-Platform Desktop',
      'Windows Native',
      'macOS Native',
      'Linux Native',
      'Desktop UI Frameworks',
      'Desktop Databases',
      'Desktop Testing',
      'Desktop Packaging & Installers',
      'Desktop Auto-Updates',
      'Desktop Performance',
      'Desktop Security',
      'Legacy Desktop Migration',
    ],
  },
  {
    id: 'embedded-iot',
    label: 'Embedded / IoT',
    topics: [
      'Microcontrollers (MCUs)',
      'Single Board Computers (SBCs)',
      'Embedded Languages',
      'Embedded IDEs & Toolchains',
      'Real-Time Operating Systems (RTOS)',
      'IoT Communication Protocols',
      'IoT Cloud Platforms',
      'Embedded Linux',
      'Sensor Programming',
      'Embedded Networking',
      'Embedded Testing & Debugging',
      'Firmware Over-the-Air (FOTA)',
      'Embedded Security',
      'Embedded Simulation',
      'Embedded CI/CD',
    ],
  },
  {
    id: 'devops-cloud',
    label: 'DevOps / cloud',
    topics: [
      'Containerization',
      'Container Orchestration',
      'Infrastructure as Code (IaC)',
      'CI/CD Pipelines',
      'Configuration Management',
      'Cloud Providers',
      'Monitoring & Observability',
      'Logging & Log Management',
      'Secrets Management',
      'Service Mesh',
      'API Gateway',
      'Load Balancing',
      'Infrastructure Monitoring',
      'Cost Management',
      'DevOps Scripting',
      'Serverless Frameworks',
      'Version Control (Git)',
    ],
  },
  {
    id: 'cybersecurity',
    label: 'Cybersecurity',
    topics: [
      'Penetration Testing',
      'Vulnerability Scanning',
      'Network Security',
      'Web Application Security',
      'Cloud Security',
      'Security Information & Event Management (SIEM)',
      'Endpoint Detection & Response (EDR)',
      'Identity & Access Management (IAM)',
      'Encryption & Cryptography',
      'Password Cracking',
      'Reverse Engineering',
      'Forensics',
      'Container & Kubernetes Security',
      'DevSecOps & SAST/DAST',
      'Social Engineering',
      'Wireless Security',
      'Red Teaming Tools',
      'Blue Teaming / Defense',
    ],
  },
  {
    id: 'data-engineering',
    label: 'Data engineering',
    topics: [
      'Data Warehousing',
      'ETL / ELT Pipelines',
      'Big Data Processing',
      'Streaming Data',
      'Data Lake & Storage',
      'Data Workflow Orchestration',
      'SQL Engines',
      'Data Transformation',
      'Data Quality & Validation',
      'Data Cataloging & Governance',
      'Data Pipeline Monitoring',
      'Data Modeling',
      'Reverse ETL',
      'Data Infrastructure as Code',
      'Data Version Control',
      'Data Engineering Languages',
    ],
  },
  {
    id: 'product-design',
    label: 'Product design',
    topics: [
      'UI Design',
      'UX Research & Testing',
      'Wireframing',
      'Prototyping',
      'Design Systems',
      'User Flow & Journey Mapping',
      'Handoff to Development',
      'Accessibility (a11y) Tools',
      'User Persona & Empathy Mapping',
      'A/B Testing (Design)',
      'Design Version Control',
      'Collaborative Design',
      'Design Feedback Tools',
      'UI Animation Tools',
      'Design Documentation',
    ],
  },
  {
    id: 'business-finance',
    label: 'Business & finance',
    topics: [
      'Financial Modeling',
      'Accounting & Bookkeeping',
      'Enterprise Resource Planning (ERP)',
      'Business Intelligence (BI)',
      'Budgeting & Forecasting',
      'Invoicing & Payments',
      'Expense Management',
      'Payroll',
      'Financial Analysis & Ratios',
      'Valuation & Investment',
      'Risk Management',
      'Compliance & Regulatory',
      'Project Finance',
      'Treasury Management',
      'Revenue Management',
      'Corporate Strategy Tools',
      'Financial Dashboards',
      'Cryptocurrency & DeFi (Finance)',
    ],
  },
  {
    id: 'photography',
    label: 'Photography',
    topics: [
      'Photo Editing (Raw Processing)',
      'Pixel-Level Editing & Retouching',
      'Batch Processing & Automation',
      'RAW Conversion',
      'Color Grading (Photos)',
      'Noise Reduction',
      'Photo Composition & Cropping',
      'HDR & Panorama Stitching',
      'Focus Stacking',
      'Photo Management & DAM',
      'Watermarking & Metadata',
      'Photo Retouching (Portrait)',
      'AI Photo Enhancement',
      'Drone Photography',
      'Product Photography',
      'Photo Portfolio & Sharing',
      'Time-Lapse Photography',
    ],
  },
  {
    id: 'music-production',
    label: 'Music production',
    topics: [
      'Digital Audio Workstations (DAWs)',
      'Audio Recording (Studio)',
      'MIDI Sequencing',
      'Audio Editing & Comping',
      'Mixing & Balancing',
      'Mastering',
      'Virtual Instruments (VSTs)',
      'Synthesizers (Software)',
      'Sampling & Beat Making',
      'Audio Effects (VST/AU)',
      'Drum Programming',
      'Audio Restoration & Repair',
      'Sound Design (From Scratch)',
      'Orchestral Composition',
      'Loop & Sample Management',
      'Music Notation & Scoring',
      'Audio-to-MIDI Conversion',
      'Live Performance Setup',
      'Podcast & Voiceover Editing',
      'Collaboration (Music)',
    ],
  },
] as const;
