/** Subtopic → technology hint strings per field (setup wizard step 3). */
export const SUBTOPIC_HINTS: Record<string, Record<string, string>> = {
  'web-development': {
    Frontend:
      'HTML, CSS, JavaScript, TypeScript, React, Vue.js, Angular, Svelte, Next.js, Nuxt.js, Astro, HTMX, Alpine.js, jQuery, Bootstrap, Tailwind CSS',
    Backend:
      'Node.js, Express, Django, Flask, FastAPI, Ruby on Rails, Laravel, Spring Boot, ASP.NET Core, Go (Gin), Phoenix (Elixir), Actix (Rust)',
    Fullstack:
      'Next.js, Nuxt.js, Remix, SvelteKit, Astro, Meteor, RedwoodJS, Blitz.js, AdonisJS, NestJS, Laravel + Inertia, Django + React, Ruby on Rails + Hotwire, Spring Boot + React, MEAN, MERN, PERN, T3 Stack, JAMstack',
    Database:
      'PostgreSQL, MySQL, MongoDB, SQLite, Redis, Firebase Firestore, DynamoDB, Cassandra, MariaDB, Supabase, Prisma, Mongoose',
    'API & integration':
      'REST, GraphQL, tRPC, Apollo Server, Apollo Client, Postman, Swagger, Hasura, WebSocket, Socket.io, gRPC',
    'DevOps & deployment':
      'Docker, Kubernetes, GitHub Actions, GitLab CI, Jenkins, Vercel, Netlify, AWS, Heroku, Render, Nginx, Apache',
    Testing: 'Jest, Vitest, Cypress, Playwright, Mocha, Chai, React Testing Library, Puppeteer, Selenium, Postman (testing)',
    'State management': 'Redux, Zustand, Pinia, Vuex, MobX, Recoil, Jotai, Context API',
    'Build tools & bundlers': 'Webpack, Vite, Parcel, Rollup, esbuild, SWC, Babel',
    'Package managers': 'npm, Yarn, pnpm, bun',
    Security: 'Helmet.js, JWT, OAuth, Passport.js, Auth0, Clerk, NextAuth, bcrypt, CORS',
    'CMS(content management)': 'WordPress, Strapi, Sanity, Contentful, Ghost, Directus, Payload CMS',
    'Analytics & monitoring': 'Google Analytics, Sentry, LogRocket, Datadog, New Relic, Grafana, Prometheus',
  },
  ai: {
    'Data Processing & ETL': 'Pandas, NumPy, Polars, Dask, Apache Spark, Hadoop, SQL, Airflow',
    'Machine Learning (ML)': 'Scikit-learn, XGBoost, LightGBM, CatBoost, MLlib, Weka',
    'Deep Learning': 'TensorFlow, PyTorch, Keras, JAX, Caffe, MXNet, Theano',
    'Natural Language Processing (NLP)': 'Hugging Face Transformers, spaCy, NLTK, Gensim, BERT, GPT, LangChain, LlamaIndex',
    'Computer Vision (CV)': 'OpenCV, YOLO, Detectron2, MediaPipe, Pillow, CLIP, SAM (Segment Anything)',
    'Reinforcement Learning': 'Stable-Baselines3, RLlib, OpenAI Gym, DeepMind Lab, Ray RLlib',
    'MLOps & Deployment': 'MLflow, Kubeflow, TFX, SageMaker, Vertex AI, ONNX, BentoML, FastAPI (for serving)',
    AutoML: 'AutoGluon, H2O.ai, TPOT, AutoKeras, PyCaret',
    'Generative AI': 'LangChain, LlamaIndex, Stable Diffusion, DALL-E, Midjourney, ElevenLabs, Whisper',
    'Prompt Engineering': 'LangChain, PromptLayer, OpenAI API, Anthropic API, Cohere',
    'Model Optimization': 'TensorRT, OpenVINO, ONNX Runtime, Quantization (PyTorch), Pruning, Distillation',
    'Data Labeling': 'Labelbox, Prodigy, Supervisely, CVAT, Roboflow',
    'Explainable AI (XAI)': 'SHAP, LIME, Captum, Eli5, InterpretML',
  },
  'game-development': {
    'Game Engines': 'Unity, Unreal Engine, Godot, GameMaker, CryEngine, Lumberyard, Defold',
    '2D Game Development': 'Unity (2D), Godot (2D), GameMaker, Pygame, Construct, ClickTeam Fusion',
    '3D Game Development': 'Unreal Engine, Unity (3D), Godot (3D), CryEngine, Source Engine',
    'Game Design & Prototyping': 'Twine, Miro, Figma (game UI), InVision, Balsamiq',
    'Physics & Simulation': 'Box2D, Bullet Physics, NVIDIA PhysX, Havok, Unity Physics, Unreal Chaos',
    'Animation & Rigging': 'Blender, Maya, 3ds Max, Spine, DragonBones, Mixamo, Unity Animation',
    'Shaders & Visual Effects (VFX)': 'Shader Graph (Unity), Material Editor (Unreal), HLSL, GLSL, Niagara VFX',
    'Audio & Sound Design': 'FMOD, Wwise, Audacity, Reaper, Unity Audio, Unreal Audio Engine',
    'Game AI': 'Behavior Trees (Unreal/Unity), GOAP, Utility AI, ML-Agents (Unity), NavMesh',
    'Multiplayer & Networking': 'Mirror, Photon, Netcode for GameObjects, Unreal Replication, AWS GameLift',
    'Game Optimization': 'Profiler (Unity/Unreal), LOD, Occlusion Culling, Draw Call Batching, Memory Profiling',
    'Version Control for Games': 'Perforce Helix, Git LFS, Plastic SCM, Subversion',
    'Mobile Game Development': 'Unity (Mobile), Unreal (Mobile), Cocos2d, SpriteKit, LibGDX',
    'Game Testing & QA': 'TestComplete, Appium, Unity Test Framework, Selenium (web games), PlaytestCloud',
    'Game Monetization': 'Unity Ads, AdMob, IronSource, Adjust, Firebase (analytics), In-App Purchase SDKs',
  },
  blockchain: {
    'Smart Contract Development': 'Solidity, Vyper, Rust (Solana), Cairo (Starknet), Michelson (Tezos), Move (Aptos/Sui)',
    'Blockchain Platforms': 'Ethereum, Solana, Binance Smart Chain (BSC), Polygon, Avalanche, Polkadot, Cosmos, Near, Flow',
    'Frameworks & Tools': 'Hardhat, Truffle, Foundry, Remix IDE, Brownie, Ape Framework, Anchor (Solana)',
    'Web3 Libraries': 'Web3.js, Ethers.js, Solana Web3.js, Vecna, Thirdweb, Moralis',
    'Wallets & Authentication': 'MetaMask, WalletConnect, Phantom, Rainbow Kit, Web3Modal, Privy, Turnkey',
    'DeFi (Decentralized Finance)': 'Uniswap (v2/v3), Aave, Compound, Curve, Balancer, MakerDAO',
    'NFTs (Non-Fungible Tokens)': 'OpenZeppelin (ERC-721, ERC-1155), IPFS, Pinata, Rarible, Alchemy NFT API',
    'Layer 2 & Scaling': 'Optimism, Arbitrum, zkSync, Polygon zkEVM, Starknet, Base, Scroll',
    Oracles: 'Chainlink, Pyth Network, Band Protocol, API3, Chronicle',
    'Indexing & Query': 'The Graph (Subgraph), Blockfrost, Covalent, Dune Analytics, Nansen',
    'Security & Auditing': 'Slither, MythX, Echidna, Consensys Diligence, Trail of Bits, CertiK, Hacken',
    'Node Infrastructure': 'Alchemy, Infura, QuickNode, RPC Provider, Geth, OpenEthereum, Erigon',
    Stablecoins: 'USDC, USDT, DAI, FRAX (understanding mechanisms: over-collateralized + algorithmic)',
    'DAOs (Decentralized Autonomous Orgs)': 'Snapshot, Aragon, Syndicate, Tally, Juicebox',
    Cryptography: 'ECDSA, Ed25519, Keccak256, SHA-3, Merkle Trees, ZK Proofs (Circom + SnarkJS)',
  },
  architecture: {
    '2D Drafting & Documentation': 'AutoCAD, DraftSight, LibreCAD, nanoCAD, BricsCAD',
    '3D Modeling & Visualization': 'SketchUp, Rhino 3D, 3ds Max, Blender, ArchiCAD, Revit (Massing), FormIt',
    'BIM (Building Information Modeling)': 'Revit, ArchiCAD, Navisworks, BIM 360, Tekla Structures, Vectorworks, Allplan',
    'Rendering & Visualization': 'V-Ray, Lumion, Enscape, Twinmotion, Corona Renderer, KeyShot, Unreal Engine (Archviz)',
    'Structural Analysis': 'SAP2000, ETABS, STAAD.Pro, Tekla Structural Designer, Robot Structural Analysis, RISA',
    'Environmental Simulation': 'Ladybug Tools, EnergyPlus, IES VE, Ecotect, ClimateStudio, Fluent (CFD)',
    'Construction Management': 'Procore, Bluebeam Revu, PlanGrid, Buildertrend, CoConstruct, Autodesk Construction Cloud',
    'Urban Planning & GIS': 'ArcGIS, QGIS, CityEngine, AutoCAD Map 3D, Google Earth Pro, Mapbox',
    'Landscape Architecture': 'LandFX, Vectorworks Landmark, Realtime Landscaping Pro, SketchUp (Landscape)',
    'Interior Architecture': 'SketchUp, Revit (Interiors), 3ds Max (Interiors), Chief Architect, HomeByMe, RoomSketcher',
    'Computational Design': 'Grasshopper (Rhino), Dynamo (Revit), Python (for CAD), Processing',
    'Site Analysis & Surveying': 'AutoCAD Civil 3D, InfraWorks, Pix4D (drone mapping), DroneDeploy, Recap Pro',
    'Project Documentation': 'Bluebeam Revu, Adobe Acrobat Pro, Notion (specs), Confluence (team docs)',
    'Code Compliance': 'UpCodes, SmartBuildings, IBC (International Building Code) checkers, Local code databases',
    'Virtual Reality (Archviz VR)': 'Enscape VR, Twinmotion VR, Unreal Engine VR, Unity VR (for archviz), IrisVR',
  },
  art: {
    'Digital Painting & Illustration': 'Adobe Photoshop, Procreate, Clip Studio Paint, Krita, Corel Painter, Rebelle, PaintTool SAI, Affinity Photo',
    'Vector Art & Graphics': 'Adobe Illustrator, CorelDRAW, Inkscape, Affinity Designer, Figma (vector), Sketch, Vectr',
    'Concept Art': 'Photoshop, Procreate, Blender (for blockout), PureRef (mood boards), 3D-Coat',
    'Traditional Art (Digital Simulation)': 'Rebelle, ArtRage, Corel Painter, Krita (wet brushes)',
    'Pixel Art': 'Aseprite, Pyxel Edit, GraphicsGale, Piskel, Photoshop (pixel grid mode)',
    '3D Sculpting & Modeling': 'ZBrush, Blender (Sculpt Mode), Mudbox, 3DCoat, Nomad Sculpt (iPad)',
    'Texture & Material Creation': 'Substance Painter, Substance Designer, Quixel Mixer, ArmorPaint, Materialize',
    'Digital Collage & Mixed Media': 'Photoshop, Illustrator, Procreate, Canva, Affinity Suite',
    Typography: 'Adobe Fonts, Google Fonts, FontForge, Glyphs, FontLab, Calligraphr',
    'Color Theory Tools': 'Adobe Color, Coolors, Paletton, Color Hunt, Colormind',
    'Composition & Perspective Tools': 'Clip Studio (perspective rulers), Procreate (drawing guides), Blender (camera framing)',
    'Art Management & Portfolio': 'ArtStation, DeviantArt, Behance, Dribbble, Adobe Portfolio, Pixpa',
    'Printmaking (Digital)': 'GIMP (screen printing sim), Inkscape (linocut), Affinity Publisher (layout)',
    'Animation (2D Hand-drawn)': 'Toon Boom Harmony, TVPaint, Krita (animation), Clip Studio Paint (animation), RoughAnimator',
    'Generative Art': 'Processing, p5.js, TouchDesigner, openFrameworks, Python (Pillow, Matplotlib)',
  },
  marketing: {
    'Digital Marketing': 'Google Ads, Meta Ads (Facebook/Instagram), LinkedIn Ads, TikTok Ads, Twitter Ads, Pinterest Ads',
    'Search Engine Optimization (SEO)': 'Google Search Console, Ahrefs, SEMrush, Moz Pro, Screaming Frog, Yoast SEO, RankMath',
    'Content Marketing': 'WordPress, Medium, HubSpot, Substack, Ghost, Notion (content planning), Airtable',
    'Email Marketing': 'Mailchimp, Klaviyo, SendGrid, Constant Contact, ConvertKit, ActiveCampaign, Brevo (Sendinblue)',
    'Social Media Management': 'Hootsuite, Buffer, Later, Sprout Social, TweetDeck, Meta Business Suite, Agorapulse',
    'Marketing Analytics': 'Google Analytics, Adobe Analytics, Mixpanel, Amplitude, Heap, Tableau, Power BI',
    'Customer Relationship Management (CRM)': 'Salesforce, HubSpot CRM, Zoho CRM, Pipedrive, Monday.com, Freshsales, Dynamics 365',
    'Marketing Automation': 'HubSpot, Marketo, Pardot, ActiveCampaign, Mailchimp (automation), Klaviyo (flows)',
    'Influencer Marketing': 'AspireIQ, Upfluence, Grin, CreatorIQ, Tagger, Heepsy',
    'Affiliate Marketing': 'ShareASale, CJ Affiliate, Rakuten Advertising, Impact, PartnerStack, Awin',
    'Landing Page Builders': 'Unbounce, Instapage, Leadpages, ClickFunnels, Carrd, Webflow',
    'A/B Testing & Optimization': 'Google Optimize, Optimizely, VWO, AB Tasty, Convert',
    'Customer Feedback & Surveys': 'Typeform, SurveyMonkey, Google Forms, Hotjar, Qualtrics, Jotform',
    'Public Relations (PR)': 'Cision, Muck Rack, Meltwater, PRWeb, Newswire',
    'Brand Strategy Tools': 'Brand24 (monitoring), Mention (listening), Miro (brand workshops), Canva (brand kit)',
    'Marketing Project Management': 'Asana, Trello, Monday.com, ClickUp, Wrike, Basecamp, Notion',
    'Video Marketing': 'YouTube Studio (analytics), Wistia, Vimeo, Loom, Hippo Video',
    'SMS Marketing': 'Twilio, Klaviyo (SMS), Attentive, Postscript, TextMagic',
    'E-commerce Marketing': 'Shopify (marketing apps), WooCommerce, BigCommerce, Amazon Ads, eBay Ads, Etsy Ads',
    'Community Marketing': 'Discord, Circle, Slack (communities), Mighty Networks, Tribe',
  },
  multimedia: {
    'Video Editing': 'Adobe Premiere Pro, Final Cut Pro, DaVinci Resolve, CapCut, Vegas Pro, iMovie, Shotcut, Clipchamp',
    'Motion Graphics & VFX': 'Adobe After Effects, Apple Motion, Fusion (DaVinci), Natron, Cavalry, Rive',
    '3D Animation': 'Blender, Maya, 3ds Max, Cinema 4D, Houdini, LightWave 3D, Cascadeur',
    'Audio Editing & Mixing': 'Adobe Audition, Audacity, Reaper, Logic Pro, Pro Tools, FL Studio, Cubase, Ableton Live',
    'Sound Design': 'Audacity, Reaper, Sound Forge, Krotos, Boom Library (samples), Arturia (synths)',
    'Music Production': 'Ableton Live, FL Studio, Logic Pro, Cubase, Studio One, Reason, Bitwig, Reaper',
    Podcasting: 'Descript, Anchor (Spotify for Podcasters), Audacity, Riverside.fm, Zencastr, Cleanfeed',
    'Visual Effects (VFX)': 'After Effects, Nuke, Fusion, HitFilm, Blender (VFX), Blackmagic Fusion',
    'Color Grading': 'DaVinci Resolve, Baselight, FilmConvert, Color Finale, Premiere Pro (Lumetri)',
    'Screen Recording & Tutorials': 'OBS Studio, Camtasia, Loom, ScreenFlow, Bandicam, ShareX',
    'Broadcasting & Streaming': 'OBS Studio, vMix, Wirecast, Streamlabs, XSplit, Restream, StreamYard',
    'Interactive Multimedia': 'TouchDesigner, Max/MSP, Processing, p5.js, VVVV, Pure Data',
    'Virtual Reality (VR) Multimedia': 'Unity VR, Unreal Engine VR, Blender (VR scene prep), Adobe Aero, Oculus Medium',
    'Augmented Reality (AR)': 'Spark AR (Meta), Lens Studio (Snapchat), 8th Wall, Adobe Aero, Unity AR Foundation',
    '3D Scanning & Photogrammetry': 'RealityCapture, Meshroom, Metashape, Polycam, Trnio, 3D Zephyr',
    'Digital Signage': 'ScreenCloud, OptiSigns, NoviSign, Yodeck, Kitcast, PiSignage',
    'Subtitling & Captioning': 'Subtitle Edit, Aegisub, DaVinci Resolve (caption tool), Otter.ai, Rev',
    'Compression & Encoding': 'HandBrake, FFmpeg, Adobe Media Encoder, Shutter Encoder, Miro Video Converter',
    'Stock Media (for practice)': 'Pexels, Pixabay, Unsplash, Coverr, Mixkit, Artgrid, Epidemic Sound',
    'Thumbnail & YouTube Graphics': 'Canva, Photoshop, GIMP, Snappa, PicMonkey, Photopea',
  },
  'mobile-development': {
    'Native Android': 'Android Studio, Kotlin, Java, Jetpack Compose, XML layouts, Gradle, ADB, Room Database',
    'Native iOS': 'Xcode, Swift, SwiftUI, UIKit, Objective-C, Core Data, TestFlight, CocoaPods',
    'Cross-Platform (Framework)': 'Flutter, React Native, .NET MAUI, Xamarin, Kotlin Multiplatform, Ionic, Capacitor',
    'Mobile UI/UX Design': 'Figma (mobile), Sketch, Adobe XD, ProtoPie, Marvel, Flinto, Principle',
    'Mobile Backend & APIs': 'Firebase (Auth, Firestore, Cloud Functions), Supabase, AWS Amplify, Back4App, Parse',
    'Mobile Databases': 'SQLite, Realm, Firebase Firestore, ObjectBox, Couchbase Lite, Room (Android), Core Data (iOS)',
    'Mobile State Management': 'Redux (React Native), BLoC (Flutter), Riverpod, MobX, Provider, ViewModel (Android), Combine (iOS)',
    'Mobile Testing': 'Espresso (Android), XCTest (iOS), Appium, Detox, Maestro, Flutter Driver, BrowserStack',
    'Mobile CI/CD': 'Bitrise, GitHub Actions, Fastlane, CircleCI, Codemagic (Flutter), App Center, TestFlight',
    'Mobile Analytics & Crash Reporting': 'Firebase Analytics, Mixpanel, Amplitude, Sentry, Crashlytics, Instabug',
    'Mobile Push Notifications': 'Firebase Cloud Messaging (FCM), Apple Push Notification Service (APNs), OneSignal, Pusher',
    'Mobile Payments & Subscriptions': 'Stripe (Mobile SDK), RevenueCat, Google Play Billing, Apple App Store Connect, PayPal SDK',
    'Mobile App Distribution': 'Google Play Console, App Store Connect, TestFlight, Firebase App Distribution, Diawi, HockeyApp',
    'Mobile Performance Optimization': 'Android Profiler, Instruments (iOS), Flutter Performance, LeakCanary, Xcode Memory Graph',
    'Mobile Security': 'ProGuard (Android), DexGuard, Obfuscation, SSL Pinning, KeyStore (Android), Keychain (iOS), SafetyNet',
  },
  'desktop-applications': {
    'Cross-Platform Desktop': 'Electron, Tauri, Qt, .NET MAUI, Flutter (Desktop), JavaFX, wxWidgets, GTK, Avalonia UI',
    'Windows Native': '.NET Framework, WPF, WinForms, UWP, WinUI 3, C#, C++, MSIX, Windows API',
    'macOS Native': 'Swift, AppKit, SwiftUI, Objective-C, Xcode, Cocoa, Mac Catalyst, Sparkle (updates)',
    'Linux Native': 'GTK, Qt (Linux), Electron, Flutter (Linux), wxWidgets, Vala, AppImage, Flatpak, Snap',
    'Desktop UI Frameworks': 'Qt Widgets, QML, React (Electron), Vue (Electron), Tkinter, PyQt, Dear ImGui',
    'Desktop Databases': 'SQLite, SQL Server Express, PostgreSQL (local), DuckDB, H2 Database, Berkeley DB',
    'Desktop Testing': 'WinAppDriver, Appium (Desktop), AutoIt, Selenium (Electron), pytest (PyQt), NUnit',
    'Desktop Packaging & Installers': 'Inno Setup, NSIS, WiX Toolset, MSI, Electron Builder, Tauri Bundler, CreateDesktopShortcut',
    'Desktop Auto-Updates': 'Electron AutoUpdater, Sparkle (macOS), WinSparkle (Windows), Squirrel, Qt Installer Framework',
    'Desktop Performance': 'Visual Studio Profiler, Instruments (macOS), PerfView, Valgrind, VTune',
    'Desktop Security': 'Code Signing (DigiCert, Comodo), Obfuscation (ConfuserEx, Dotfuscator), Anti-Debugging, Secure Storage',
    'Legacy Desktop Migration': 'VB6 to .NET, Win32 to UWP, Delphi, PowerBuilder, FoxPro, Access to SQL Server',
  },
  'embedded-iot': {
    'Microcontrollers (MCUs)': 'Arduino, ESP32, ESP8266, STM32, PIC, AVR, MSP430, Raspberry Pi Pico (RP2040)',
    'Single Board Computers (SBCs)': 'Raspberry Pi, BeagleBone, NVIDIA Jetson, Orange Pi, Odroid, Asus Tinker Board',
    'Embedded Languages': 'C, C++, MicroPython, CircuitPython, Rust (embedded), Assembly (ARM, AVR), zig',
    'Embedded IDEs & Toolchains': 'Arduino IDE, PlatformIO, MPLAB X, STM32CubeIDE, Keil uVision, IAR Embedded Workbench, Eclipse',
    'Real-Time Operating Systems (RTOS)': 'FreeRTOS, Zephyr, VxWorks, ThreadX, Mbed OS, RIOT OS, QNX, uC/OS',
    'IoT Communication Protocols': 'MQTT, CoAP, HTTP/HTTPS (REST), WebSocket, LoRaWAN, Zigbee, Z-Wave, BLE, Modbus, CAN Bus',
    'IoT Cloud Platforms': 'AWS IoT Core, Azure IoT Hub, Google Cloud IoT, ThingSpeak, Particle, Blynk, Ubidots',
    'Embedded Linux': 'Yocto Project, Buildroot, OpenWrt, Raspbian, Ubuntu Core, BalenaOS, Petalinux',
    'Sensor Programming': 'I2C, SPI, UART, GPIO, ADC, PWM, Accelerometer, Gyroscope, Temperature (DHT22, DS18B20)',
    'Embedded Networking': 'Ethernet (TCP/IP stack), WiFi (ESP8266/ESP32), BLE (Bluetooth Low Energy), LoRa, LTE-M, NB-IoT',
    'Embedded Testing & Debugging': 'JTAG, SWD, GDB (Remote), Serial Monitor, Logic Analyzer (Saleae), Oscilloscope, printf debugging',
    'Firmware Over-the-Air (FOTA)': 'MQTT OTA, AWS OTA, Azure Device Update, Balena, JFrog Connect, Memfault',
    'Embedded Security': 'Secure Boot, TPM, Hardware Security Module (HSM), TrustZone (ARM), Secure Element (ATECC608A)',
    'Embedded Simulation': 'QEMU, Unicorn Engine, Wokwi, Tinkercad Circuits, Simulink (Embedded Coder)',
    'Embedded CI/CD': 'PlatformIO CI, GitHub Actions (Embedded), GitLab CI (for MCU), Jenkins (cross-compile)',
  },
  'devops-cloud': {
    Containerization: 'Docker, Podman, LXC, containerd, rkt, Buildah',
    'Container Orchestration': 'Kubernetes (k8s), Docker Swarm, Amazon ECS, Apache Mesos, Nomad, Rancher, OpenShift',
    'Infrastructure as Code (IaC)': 'Terraform, AWS CloudFormation, Pulumi, Ansible, Chef, Puppet, Bicep (Azure), CDK',
    'CI/CD Pipelines': 'GitHub Actions, GitLab CI, Jenkins, CircleCI, Azure DevOps, Bitbucket Pipelines, TeamCity, Bamboo',
    'Configuration Management': 'Ansible, Chef, Puppet, SaltStack, CFEngine',
    'Cloud Providers': 'AWS (Amazon Web Services), Microsoft Azure, Google Cloud Platform (GCP), DigitalOcean, Linode, Vultr',
    'Monitoring & Observability': 'Prometheus, Grafana, Datadog, New Relic, Nagios, Zabbix, Dynatrace, Sentry, Elastic Stack (ELK)',
    'Logging & Log Management': 'ELK Stack (Elasticsearch, Logstash, Kibana), Loki, Splunk, Fluentd, Graylog, Papertrail',
    'Secrets Management': 'HashiCorp Vault, AWS Secrets Manager, Azure Key Vault, Google Secret Manager, Doppler, SOPS',
    'Service Mesh': 'Istio, Linkerd, Consul, Kuma, Traefik Mesh, Cilium',
    'API Gateway': 'Kong, NGINX, Traefik, AWS API Gateway, Azure API Management, Apigee, Envoy',
    'Load Balancing': 'NGINX, HAProxy, AWS ELB/ALB, Traefik, F5 Big-IP, Apache (mod_proxy_balancer)',
    'Infrastructure Monitoring': 'AWS CloudWatch, Azure Monitor, Google Cloud Monitoring, Prometheus, Datadog',
    'Cost Management': 'AWS Cost Explorer, CloudHealth (VMware), CloudCheckr, Kubecost, Vantage',
    'DevOps Scripting': 'Bash, Python, Go (for DevOps tools), Ruby (Chef/Puppet), Groovy (Jenkins)',
    'Serverless Frameworks': 'AWS Lambda, Serverless Framework, Azure Functions, Google Cloud Functions, Vercel, Netlify Functions',
    'Version Control (Git)': 'Git, GitHub, GitLab, Bitbucket, Azure Repos',
  },
  cybersecurity: {
    'Penetration Testing': 'Kali Linux, Metasploit, Burp Suite, OWASP ZAP, Nmap, SQLmap, Nikto, Wireshark, John the Ripper',
    'Vulnerability Scanning': 'Nessus, OpenVAS, Qualys, Nexpose, Acunetix, Intruder, Snyk, Trivy',
    'Network Security': 'Wireshark, tcpdump, Snort, Zeek (Bro), Suricata, pfSense, Cisco ASA, iptables, nftables',
    'Web Application Security': 'Burp Suite, OWASP ZAP, SQLmap, Nikto, Dirb, GoBuster, wpscan, Nuclei',
    'Cloud Security': 'AWS Security Hub, Azure Security Center, GCP Security Command Center, Prisma Cloud, Lacework, Wiz',
    'Security Information & Event Management (SIEM)': 'Splunk, Elastic SIEM, QRadar, LogRhythm, Azure Sentinel, Sumo Logic, Graylog',
    'Endpoint Detection & Response (EDR)': 'CrowdStrike Falcon, Carbon Black, SentinelOne, Microsoft Defender for Endpoint, Cylance',
    'Identity & Access Management (IAM)': 'Okta, Microsoft Entra ID (Azure AD), Auth0, Keycloak, Ping Identity, ForgeRock',
    'Encryption & Cryptography': 'OpenSSL, GnuPG (GPG), VeraCrypt, LUKS, HashCat, OpenSSL, age, cryptsetup',
    'Password Cracking': 'John the Ripper, HashCat, Hydra, Cain & Abel, L0phtCrack, CeWL (custom wordlist)',
    'Reverse Engineering': 'Ghidra, IDA Pro, Radare2, x64dbg, OllyDbg, dnSpy (.NET), gdb, objdump',
    Forensics: 'Autopsy (Sleuth Kit), FTK Imager, Volatility (memory forensics), RedLine, Wireshark (forensics)',
    'Container & Kubernetes Security': 'Docker Bench, kube-bench, kube-hunter, Falco, Trivy, Aqua Security',
    'DevSecOps & SAST/DAST': 'SonarQube, Checkmarx, Fortify, Snyk, OWASP Dependency-Check, Semgrep, Bandit (Python)',
    'Social Engineering': 'Gophish, SET (Social Engineering Toolkit), Evilginx2, Modlishka',
    'Wireless Security': 'Aircrack-ng, Kismet, Reaver, Wifite, BetterCAP, Bluetooth (Ubertooth)',
    'Red Teaming Tools': 'Cobalt Strike, Mythic, Covenant, Empire, Caldera, Atomic Red Team, BloodHound',
    'Blue Teaming / Defense': 'Snort, Suricata, Security Onion, Wazuh, OSSEC, Tripwire, SELinux, AppArmor',
  },
  'data-engineering': {
    'Data Warehousing': 'Snowflake, Amazon Redshift, Google BigQuery, Azure Synapse, Databricks SQL, Teradata',
    'ETL / ELT Pipelines': 'Apache Airflow, dbt (Data Build Tool), Apache NiFi, Talend, Informatica, Pentaho, Stitch',
    'Big Data Processing': 'Apache Spark, Apache Flink, Apache Hadoop (HDFS, MapReduce), Apache Beam, Dask, Ray',
    'Streaming Data': 'Apache Kafka, Apache Pulsar, Amazon Kinesis, RabbitMQ (streaming), Redpanda, Google Pub/Sub',
    'Data Lake & Storage': 'AWS S3, Azure Data Lake Storage (ADLS), Google Cloud Storage (GCS), HDFS, Delta Lake, Apache Iceberg',
    'Data Workflow Orchestration': 'Apache Airflow, Dagster, Prefect, Luigi, Argo Workflows, AWS Step Functions',
    'SQL Engines': 'PostgreSQL, Trino (Presto), Apache Drill, Spark SQL, Dremio, ClickHouse, DuckDB',
    'Data Transformation': 'dbt, Spark (DataFrame API), Pandas (for smaller data), SQL (CTEs, window functions)',
    'Data Quality & Validation': 'Great Expectations, Deequ, Soda SQL, dbt tests, Apache Griffin, Monte Carlo',
    'Data Cataloging & Governance': 'Apache Atlas, Amundsen, DataHub (LinkedIn), Collibra, Alation, Purview (Azure)',
    'Data Pipeline Monitoring': 'Datadog (data pipelines), Monte Carlo, Bigeye, Datafold, Elementary, Astronomer',
    'Data Modeling': 'dbt (semantic layer), LookML (Looker), Tableau (data modeling), ER/Studio, dbdiagram.io',
    'Reverse ETL': 'Hightouch, Census, Polytomic, Grouparoo, RudderStack (reverse ETL)',
    'Data Infrastructure as Code': 'Terraform (data pipelines), AWS CDK (for data), Pulumi, CloudFormation',
    'Data Version Control': 'DVC (Data Version Control), LakeFS, Git LFS (for data), Delta Lake (time travel)',
    'Data Engineering Languages': 'Python (PySpark, Pandas), SQL, Scala (Spark), Java (Kafka, Flink), Go (data pipelines)',
  },
  'product-design': {
    'UI Design': 'Figma, Sketch, Adobe XD, Framer, Lunacy, Penpot, InVision Studio, Axure RP',
    'UX Research & Testing': 'UserTesting, Maze, Lookback, Hotjar, Crazy Egg, Optimal Workshop, Dovetail, UserZoom',
    Wireframing: 'Balsamiq, Figma (wireframes), Sketch (low-fi), Wireframe.cc, Mockplus, Whimsical',
    Prototyping: 'Figma (prototype), InVision, ProtoPie, Framer, Axure RP, Marvel, Principle, Flinto',
    'Design Systems': 'Figma (components), Storybook (design + dev), Zeroheight, Supernova, Backlight',
    'User Flow & Journey Mapping': 'Miro, Mural, Lucidchart, Whimsical (flowcharts), UXPressia, Smaply, FlowMapp',
    'Handoff to Development': 'Zeplin, Figma Dev Mode, Avocode, InVision Inspect, Supernova (design tokens), Framer',
    'Accessibility (a11y) Tools': 'Stark (Figma/Sketch), Axe (Deque), Wave, Lighthouse (a11y), Color Contrast Analyzer',
    'User Persona & Empathy Mapping': 'Miro, Mural, Xtensio, Userforge, Smaply, UXPressia',
    'A/B Testing (Design)': 'Optimizely (visual editor), Google Optimize, VWO (visual editor), Unbounce',
    'Design Version Control': 'Figma version history, Abstract (Sketch), Plant, Kactus (design git)',
    'Collaborative Design': 'Figma (real-time), Miro, Whimsical, Conceptboard, Lucidspark',
    'Design Feedback Tools': 'InVision (comments), Zeplin (feedback), Pastel, BugHerd (visual feedback), Markly',
    'UI Animation Tools': 'Principle, Flinto, After Effects (with Lottie), Figma Smart Animate, Rive',
    'Design Documentation': 'Notion (design docs), Confluence, Zeroheight (design system docs), Slab, Nuclino',
  },
  'business-finance': {
    'Financial Modeling': 'Microsoft Excel (advanced), Google Sheets (complex formulas), Quantrix, Oracle Hyperion',
    'Accounting & Bookkeeping': 'QuickBooks, Xero, FreshBooks, Sage, Wave, Zoho Books, Odoo, NetSuite',
    'Enterprise Resource Planning (ERP)': 'SAP, Oracle ERP, Microsoft Dynamics 365, NetSuite, Odoo, Infor, Epicor',
    'Business Intelligence (BI)': 'Tableau, Power BI, Looker (Google), Qlik Sense, Domo, Metabase, Redash',
    'Budgeting & Forecasting': 'PlanGuru, Anaplan, Vena Solutions, Centage, Prophix, IBM Planning Analytics',
    'Invoicing & Payments': 'Stripe, PayPal, Square, FreshBooks (invoicing), Zoho Invoice, Wave, Xero (invoicing)',
    'Expense Management': 'Expensify, Concur (SAP), Rydoo, Brex, Divvy, Fyle, Spendesk',
    Payroll: 'Gusto, ADP, Paychex, BambooHR (payroll), QuickBooks Payroll, Rippling',
    'Financial Analysis & Ratios': 'Excel (financial functions), Python (Pandas, NumPy), R (tidyquant), MATLAB, QuantConnect',
    'Valuation & Investment': 'Bloomberg Terminal, Capital IQ, PitchBook, FactSet, Morningstar Direct, Yahoo Finance API',
    'Risk Management': 'RiskWatch, LogicManager, Palisade (Risk), SAS Risk Management, Active Risk Manager (ARM)',
    'Compliance & Regulatory': 'AuditBoard, NAVEX Global, LogicGate, ServiceNow GRC, MetricStream, OneTrust',
    'Project Finance': 'Oracle Primavera, Microsoft Project (finance module), Procore (finance), Aconex',
    'Treasury Management': 'Kyriba, Coupa (Treasury), GTreasury, TreasuryXpress, Bellin, Sage Intacct',
    'Revenue Management': 'Salesforce CPQ, Zuora (subscription), Maxio (formerly SaaSOptics), Chargebee',
    'Corporate Strategy Tools': 'Miro (strategy mapping), Strategyzer (Business Model Canvas), Cascade, BSC Designer',
    'Financial Dashboards': 'Tableau (Finance dashboards), Power BI (KPIs), Google Looker Studio, Klipfolio, Geckoboard',
    'Cryptocurrency & DeFi (Finance)': 'CoinGecko API, CoinMarketCap API, DeFi Llama, Dune Analytics (finance dashboards)',
  },
  photography: {
    'Photo Editing (Raw Processing)': 'Adobe Lightroom, Capture One, DxO PhotoLab, Luminar Neo, ON1 Photo RAW, Darktable (open source)',
    'Pixel-Level Editing & Retouching': 'Adobe Photoshop, Affinity Photo, GIMP, Pixelmator Pro, Corel PaintShop Pro, Photopea (browser)',
    'Batch Processing & Automation': 'Adobe Lightroom (batch), Photoshop Actions, Capture One (batch), FastStone Image Viewer',
    'RAW Conversion': 'Adobe Camera Raw (ACR), Capture One (RAW), DxO PureRAW, RawTherapee, Canon DPP, Nikon NX Studio',
    'Color Grading (Photos)': 'Adobe Lightroom (color grading), Capture One (color editor), DaVinci Resolve (for photo color)',
    'Noise Reduction': 'DxO DeepPRIME, Topaz DeNoise AI, Lightroom (AI Denoise), ON1 NoNoise AI, Neat Image',
    'Photo Composition & Cropping': 'Photoshop (crop tools), Lightroom (guided crop), GIMP, Affinity Photo, Figma (basic crop)',
    'HDR & Panorama Stitching': 'Adobe Lightroom (HDR/Pano), Photoshop (merge), PTGui, Hugin (open source), Affinity Photo',
    'Focus Stacking': 'Helicon Focus, Zerene Stacker, Photoshop (auto-blend layers), Affinity Photo',
    'Photo Management & DAM': 'Adobe Bridge, Lightroom (catalog), Photo Mechanic, DigiKam, Eagle, Mylio, Peakto',
    'Watermarking & Metadata': 'Lightroom (watermark), Photoshop (batch watermark), ExifTool, Photo Mechanic (metadata)',
    'Photo Retouching (Portrait)': 'Photoshop (liquify, frequency separation), PortraitPro, Luminar Neo (portrait), Evoto',
    'AI Photo Enhancement': 'Topaz Gigapixel (upscale), Topaz Photo AI, Luminar Neo (AI), Remini (face enhancement)',
    'Drone Photography': 'Adobe Lightroom (drone photos), DJI Fly (editing), DroneDeploy (mapping), Pix4Dcapture',
    'Product Photography': 'Photoshop (clipping paths, background removal), Capture One (color accuracy), Clipping Magic',
    'Photo Portfolio & Sharing': 'Adobe Portfolio, SmugMug, Zenfolio, Pixieset, Flickr, 500px, Format',
    'Time-Lapse Photography': 'LRTimelapse (editing), Lightroom (time-lapse sequence), After Effects (time-lapse assembly)',
  },
  'music-production': {
    'Digital Audio Workstations (DAWs)': 'Ableton Live, FL Studio, Logic Pro (macOS), Cubase, Pro Tools, Studio One, Reaper, Bitwig, Cakewalk, GarageBand',
    'Audio Recording (Studio)': 'Pro Tools (recording), Logic Pro (recording), Audacity, Reaper, Cubase, Studio One',
    'MIDI Sequencing': 'Ableton Live (MIDI), FL Studio (piano roll), Logic Pro (MIDI), Cubase (MIDI), Reaper (MIDI)',
    'Audio Editing & Comping': 'Pro Tools (Elastic Time), Logic Pro (Flex Time), Reaper (comping), Cubase (audio warp), Audacity',
    'Mixing & Balancing': 'Any DAW (built-in mixer), Pro Tools (mixing focus), Logic Pro (console emulation), Studio One (mix engine)',
    Mastering: 'iZotope Ozone, LANDR (AI mastering), Steinberg WaveLab, Ableton Live (master chain), Logic Pro (mastering tools)',
    'Virtual Instruments (VSTs)': 'Native Instruments (Kontakt, Massive), Serum (Xfer), Omnisphere, Sylenth1, Arturia (V Collection), Spitfire Audio',
    'Synthesizers (Software)': 'Serum, Massive X, Vital (free), Pigments (Arturia), Phase Plant, Diva (u-he)',
    'Sampling & Beat Making': 'Ableton (Simpler/Sampler), FL Studio (Sampler), Logic (Quick Sampler), MPC (software), Serato Sample',
    'Audio Effects (VST/AU)': 'iZotope (RX, Neutron), ValhallaDSP (reverb), Soundtoys (effects), FabFilter (EQ/comp), Waves (bundle)',
    'Drum Programming': 'FL Studio (step sequencer), Ableton (Drum Rack), Logic (Drummer), EZDrummer (realistic drums), Superior Drummer',
    'Audio Restoration & Repair': 'iZotope RX (audio repair), Adobe Audition (restoration), Audacity (noise reduction), Acon Digital Restoration',
    'Sound Design (From Scratch)': 'Serum (wavetable), Vital (free), Phase Plant, Massive X, Harmor (FL Studio), Zebra (u-he)',
    'Orchestral Composition': 'Spitfire Audio (BBC Symphony), EastWest (Hollywood Orchestra), Native Instruments (Symphony Series), NotePerformer',
    'Loop & Sample Management': 'Splice (sample finder), Loopcloud, ADSR Sample Manager, Native Instruments Battery (sample management)',
    'Music Notation & Scoring': 'Sibelius, Finale, Dorico, MuseScore (free), Noteflight (browser)',
    'Audio-to-MIDI Conversion': 'Ableton (audio to MIDI), Melodyne (DNA), Cubase (audio to MIDI), Logic (audio to MIDI)',
    'Live Performance Setup': 'Ableton Live (session view), MainStage (macOS), Bitwig (live), StageLight (usine)',
    'Podcast & Voiceover Editing': 'Audacity (voice), Adobe Audition (podcast), Descript (voice editing), Reaper (voiceover)',
    'Collaboration (Music)': 'Splice Studio, BandLab, Soundtrap (browser), Endlesss (jam), Sessionwire (pro tools collab)',
  },
};
