'use client';

import React from 'react';
import Link from 'next/link';
import { useSkillTest } from '@/app/skill-test/SkillTestRuntimeContext';
import { FIELD_OPTIONS } from '@/app/skill-test/fieldOptions';
import { SkillFieldIcon } from '@/app/skill-test/SkillFieldIcon';
import {
  DIFFICULTY_OPTIONS,
  INTRO_RULE_CHECKLIST,
  LANGUAGE_OPTIONS,
  SESSION_DURATION_MINUTES,
  SETUP_STEPS,
  formatSessionDuration,
} from '@/app/skill-test/constants';

export function SkillTestSetupPhase() {
  const {
    stripePaymentRequired,
    examFeeLabel,
    paymentBusy,
    paymentStatusLoading,
    hasExamPaymentCredit,
    beginCheckout,
    payment,
    setupPhase,
    setSetupPhase,
    setupStep,
    setSetupStep,
    introRulesAck,
    setIntroRulesAck,
    selectedField,
    setSelectedField,
    selectedLanguages,
    setSelectedLanguages,
    selectedTopics,
    setSelectedTopics,
    difficulty,
    setDifficulty,
    err,
    setErr,
    sessionRecording,
    allIntroRulesAcknowledged,
    currentSubtopicHints,
    selectedSubtopic,
    selectedSubtopicHint,
    subtopicProgramOptions,
    selectedFieldConfig,
    languageChoices,
    start,
  } = useSkillTest();

  return (
        <div className="flex min-h-0 flex-1 flex-col">
          <div className="min-h-0 flex-1 overflow-y-auto pb-3 [-webkit-overflow-scrolling:touch]">
            {setupPhase === 'intro' ? (
              <div className="w-full border-0 bg-transparent p-0 shadow-none">
                <div className="mx-auto w-full max-w-none">
            <p className="text-xs font-sans font-semibold uppercase tracking-wide text-stone-600">Before you begin</p>
            <h2 className="mt-2 text-2xl font-semibold italic tracking-tight text-ink sm:text-3xl">Test details &amp; rules</h2>
            <p className="mt-3 text-base leading-relaxed text-ink-muted">
              Read this overview once. After you continue, you will choose difficulty, field, language, and subtopics—then your
              personalized test will be generated.
            </p>

            <div className="mt-8 space-y-8">
              <section className="border-l-2 border-[#1e293b]/35 pl-5">
                <h3 className="text-lg font-semibold italic text-ink">What this test includes</h3>
                <ul className="mt-3 list-inside list-disc space-y-2 text-ink-muted marker:text-[#4f46e5]">
                  <li>
                    <strong className="font-semibold text-ink">Part 1 — Multiple choice (25):</strong> Select the best answer for each
                    question.
                  </li>
                  <li>
                    <strong className="font-semibold text-ink">Part 2 — Written (10):</strong> Write clear responses in your own words.
                  </li>
                  <li>
                    <strong className="font-semibold text-ink">Part 3 — Correcting mistakes (15):</strong> Identify issues and provide corrected versions.
                  </li>
                  <li>
                    <strong className="font-semibold text-ink">Part 4 — Practical challenges (2):</strong> Two deeper scenarios aligned with your
                    field.
                  </li>
                  <li>
                    <strong className="font-semibold text-ink">Part 5 — AI interview (5):</strong> Video-style rounds — questions spoken aloud, you answer on camera by voice (no on-screen text).
                  </li>
                </ul>
                <p className="mt-4 text-sm leading-relaxed text-ink-soft">
                  Questions are generated by AI based on your difficulty, field, language, and selected subtopics. Your score combines
                  automatic grading (multiple choice) and AI evaluation (written parts).
                </p>
              </section>

              <section className="border-l-2 border-[#6366f1]/45 pl-5">
                <h3 className="text-lg font-semibold italic text-ink">Rules</h3>
                <p className="mt-2 font-sans text-sm text-ink-soft">
                  Read each rule and check the box beside it. You can continue to setup only after every rule is acknowledged.
                </p>
                <fieldset className="mt-4 space-y-3 border-0 p-0">
                  <legend className="sr-only">Acknowledge each rule</legend>
                  {INTRO_RULE_CHECKLIST.map((rule) => {
                    const checked = Boolean(introRulesAck[rule.id]);
                    return (
                      <label
                        key={rule.id}
                        className={`flex cursor-pointer gap-3 rounded-md border px-3 py-3 font-sans transition-colors sm:px-4 ${
                          checked
                            ? 'border-[#4f46e5]/55 bg-[#0f172a]/[0.05]'
                            : 'border-[#1e293b]/25 bg-transparent hover:border-[#4f46e5]/35 hover:bg-[#0f172a]/[0.03]'
                        }`}
                      >
                        <input
                          type="checkbox"
                          checked={checked}
                          onChange={() =>
                            setIntroRulesAck((prev) => ({
                              ...prev,
                              [rule.id]: !prev[rule.id],
                            }))
                          }
                          className="mt-1 h-4 w-4 shrink-0 rounded border-[#1e293b]/55 text-[#4f46e5] focus:ring-2 focus:ring-[#4f46e5]/40"
                        />
                        <span className="text-sm leading-relaxed text-ink-muted">{rule.text}</span>
                      </label>
                    );
                  })}
                </fieldset>
                {!allIntroRulesAcknowledged && (
                  <p className="mt-3 font-sans text-xs font-medium text-[#8b5e00]" role="status">
                    Confirm all rules above to unlock continue.
                  </p>
                )}
              </section>
            </div>
          </div>
              </div>
            ) : (
          <div className="w-full">
            <div className="w-full border-0 bg-transparent p-0 shadow-none sm:p-1">
              <div className="grid gap-8 lg:grid-cols-[minmax(0,220px)_1fr]">
                <aside className="border-b border-[#1e293b]/25 pb-6 md:border-b-0 md:border-r md:pb-0 md:pr-8">
                  <h3 className="text-2xl font-semibold italic text-ink">Skill Test</h3>
                  <p className="mt-1 text-xl font-semibold text-stone-800">Step {setupStep} of {SETUP_STEPS.length}</p>
                  <div className="mt-6 space-y-4">
                    {SETUP_STEPS.map((step) => {
                      const isDone = setupStep > step.id;
                      const isCurrent = setupStep === step.id;
                      return (
                        <div key={step.id} className="flex items-center gap-3 font-sans text-sm font-semibold">
                          <div
                            className={`flex h-7 w-7 items-center justify-center rounded-full border text-xs ${
                              isDone
                                ? 'border-[#4f46e5] bg-[#4f46e5] text-white'
                                : isCurrent
                                  ? 'border-slate-900 bg-slate-900 text-white'
                                  : 'border-stone-300 bg-parchment-50 text-slate-500'
                            }`}
                          >
                            {isDone ? '✓' : step.id}
                          </div>
                          <span className={isCurrent ? 'font-sans font-semibold text-ink underline decoration-[#6366f1] underline-offset-4' : 'font-sans text-ink-soft'}>
                            {step.label}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                </aside>

                <div className="border-l-2 border-[#6366f1]/40 pl-6 lg:pr-0">
                  <p className="text-sm leading-7 text-ink-soft">
                    Complete this quick setup to generate a personalized AI skill test.
                  </p>

                  {setupStep === 1 && (
                    <div className="mt-7 space-y-5">
                      <h4 className="text-2xl font-semibold italic tracking-tight text-ink md:text-3xl">
                        Choose difficulty level
                      </h4>
                      <fieldset className="space-y-2 border-0 p-0">
                        <legend className="sr-only">Difficulty level</legend>
                        {DIFFICULTY_OPTIONS.map((opt) => {
                          const selected = difficulty === opt.value;
                          return (
                            <label
                              key={opt.value}
                              className={`flex cursor-pointer gap-4 rounded-sm border px-4 py-3.5 font-sans outline-none ring-offset-2 ring-offset-white transition-colors focus-within:ring-2 focus-within:ring-[#6366f1]/50 sm:items-center ${
                                selected
                                  ? 'border-[#4f46e5] bg-[#0f172a]/[0.06] shadow-[inset_3px_0_0_0_#4f46e5]'
                                  : 'border-[#1e293b]/30 bg-transparent hover:border-[#4f46e5]/45 hover:bg-[#0f172a]/[0.03]'
                              }`}
                            >
                              <input
                                type="radio"
                                name="difficulty"
                                value={opt.value}
                                checked={selected}
                                onChange={() => setDifficulty(opt.value)}
                                className="sr-only"
                              />
                              <span
                                className={`mt-0.5 flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-[3px] border-2 sm:mt-0 ${
                                  selected ? 'border-[#4f46e5] bg-[#4f46e5]' : 'border-[#1e293b]/70 bg-parchment-50/90'
                                }`}
                                aria-hidden
                              >
                                {selected && (
                                  <svg className="h-2.5 w-2.5 text-white" viewBox="0 0 12 12" fill="none" aria-hidden>
                                    <path
                                      d="M2.5 6.5 L5 9 L9.5 3.5"
                                      stroke="currentColor"
                                      strokeWidth="1.8"
                                      strokeLinecap="round"
                                      strokeLinejoin="round"
                                    />
                                  </svg>
                                )}
                              </span>
                              <span className="min-w-0 flex-1 text-left">
                                <span className="block text-sm font-semibold text-ink">{opt.label}</span>
                                <span className="mt-0.5 block text-xs leading-snug text-ink-soft">{opt.description}</span>
                              </span>
                            </label>
                          );
                        })}
                      </fieldset>
                    </div>
                  )}

                  {setupStep === 2 && (
                    <div className="mt-7 space-y-5">
                      <div>
                        <h4 className="text-2xl font-semibold italic tracking-tight text-ink md:text-3xl">Choose your field</h4>
                        <p className="mt-2 max-w-2xl font-sans text-sm leading-relaxed text-ink-soft">
                          These domains match the tracks in{' '}
                          <Link
                            href="/learning-world"
                            className="font-semibold text-ink underline decoration-parchment-400 underline-offset-[3px] transition hover:decoration-parchment-800"
                          >
                            Learning World
                          </Link>
                          . Select the area to evaluate here; you&apos;ll pick a subtopic next.
                        </p>
                      </div>
                      <fieldset className="border-0 p-0">
                        <legend className="sr-only">Professional field</legend>
                        <div className="grid max-h-[min(520px,calc(100dvh-20rem))] grid-cols-1 gap-3 overflow-y-auto pr-1 sm:grid-cols-2">
                          {FIELD_OPTIONS.map((field) => {
                            const selected = selectedField === field.id;
                            return (
                              <label
                                key={field.id}
                                className={`group flex cursor-pointer flex-col rounded-xl border px-3 py-3 font-sans shadow-sm outline-none ring-offset-2 ring-offset-white transition focus-within:ring-2 focus-within:ring-[#6366f1]/50 sm:px-3.5 sm:py-3.5 ${
                                  selected
                                    ? 'border-[#4f46e5] bg-[#0f172a]/[0.07] shadow-[0_2px_12px_rgba(15,23,42,0.08)]'
                                    : 'border-[#1e293b]/28 bg-parchment-50/50 hover:border-[#4f46e5]/55 hover:bg-[#0f172a]/[0.04]'
                                }`}
                              >
                                <input
                                  type="radio"
                                  name="field"
                                  value={field.id}
                                  checked={selected}
                                  onChange={() => setSelectedField(field.id)}
                                  className="sr-only"
                                />
                                <div className="flex items-start gap-2.5">
                                  <SkillFieldIcon fieldId={field.id} variant="picker" />
                                  <div className="min-w-0 flex-1">
                                    <div className="flex items-start justify-between gap-2">
                                      <span className="block text-[1rem] font-semibold leading-snug text-ink [overflow-wrap:anywhere]">
                                        {field.label}
                                      </span>
                                      <span
                                        className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border-2 transition-colors ${
                                          selected
                                            ? 'border-parchment-800 bg-parchment-800 shadow-[0_0_0_2px_rgba(255,248,235,0.88)]'
                                            : 'border-parchment-500/60 bg-parchment-100'
                                        }`}
                                        aria-hidden
                                      >
                                        {selected && (
                                          <svg className="h-2.5 w-2.5 text-white" viewBox="0 0 12 12" fill="none" aria-hidden>
                                            <path
                                              d="M2.5 6.5 L5 9 L9.5 3.5"
                                              stroke="currentColor"
                                              strokeWidth="1.8"
                                              strokeLinecap="round"
                                              strokeLinejoin="round"
                                            />
                                          </svg>
                                        )}
                                      </span>
                                    </div>
                                    <span className="mt-0.5 block text-xs leading-snug text-ink-soft">
                                      {field.topics.length} specialization options
                                    </span>
                                    <div className="mt-2 flex flex-wrap gap-1">
                                      {field.topics.slice(0, 4).map((topic) => (
                                        <span
                                          key={`${field.id}-${topic}`}
                                          className="max-w-full truncate rounded bg-parchment-200/55 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-ink-soft ring-1 ring-inset ring-parchment-300/45"
                                        >
                                          {topic}
                                        </span>
                                      ))}
                                      {field.topics.length > 4 ? (
                                        <span className="rounded px-1.5 py-0.5 text-[10px] font-semibold text-ink-soft">
                                          +{field.topics.length - 4}
                                        </span>
                                      ) : null}
                                    </div>
                                  </div>
                                </div>
                              </label>
                            );
                          })}
                        </div>
                      </fieldset>
                    </div>
                  )}

                  {setupStep === 3 && (
                    <div className="mt-7 space-y-4">
                      <h4 className="text-2xl font-semibold italic tracking-tight text-ink md:text-3xl">Choose a subtopic</h4>
                      <p className="text-sm leading-7 text-ink-soft">
                        Pick one specialization area in {selectedFieldConfig?.label ?? 'your selected field'}.
                      </p>
                      <div className="grid gap-2 md:max-h-[420px] md:overflow-y-auto md:pr-1">
                        {(FIELD_OPTIONS.find((f) => f.id === selectedField)?.topics ?? []).map((topic) => {
                          const checked = selectedTopics.includes(topic);
                          const hint = currentSubtopicHints?.[topic];
                          return (
                            <label key={topic} className="flex cursor-pointer items-start gap-2.5 rounded-sm border border-[#1e293b]/35 bg-transparent px-3 py-2 text-sm text-ink-muted hover:border-[#4f46e5]/55 hover:bg-[#0f172a]/[0.04]">
                              <input
                                type="radio"
                                name="selected-subtopic"
                                checked={checked}
                                onChange={(e) => {
                                  setSelectedTopics(e.target.checked ? [topic] : []);
                                }}
                                className="sr-only"
                              />
                              <span
                                className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border-2 transition-colors ${
                                  checked
                                    ? 'border-parchment-800 bg-parchment-800 shadow-[0_0_0_2px_rgba(255,248,235,0.88)]'
                                    : 'border-parchment-500/60 bg-parchment-100'
                                }`}
                                aria-hidden
                              >
                                {checked && (
                                  <svg className="h-2.5 w-2.5 text-white" viewBox="0 0 12 12" fill="none" aria-hidden>
                                    <path
                                      d="M2.5 6.5 L5 9 L9.5 3.5"
                                      stroke="currentColor"
                                      strokeWidth="1.8"
                                      strokeLinecap="round"
                                      strokeLinejoin="round"
                                    />
                                  </svg>
                                )}
                              </span>
                              <span className="min-w-0 flex-1">
                                <span className="block text-sm font-semibold leading-snug text-ink">{topic}</span>
                                {hint && <span className="mt-1 block text-xs leading-relaxed text-ink-soft">{hint}</span>}
                              </span>
                            </label>
                          );
                        })}
                      </div>
                      {selectedSubtopic && selectedSubtopicHint && (
                        <div className="mt-3 overflow-hidden rounded-md border border-[#1e293b]/30 bg-[#0f172a]/[0.02]">
                          <div className="grid grid-cols-1 border-b border-[#1e293b]/25 bg-[#0f172a]/[0.04] px-3 py-2 text-xs font-semibold uppercase tracking-wide text-ink-soft sm:grid-cols-[200px_1fr] sm:px-4">
                            <span>Role Category</span>
                            <span>Specific Programs / Tools</span>
                          </div>
                          <div className="grid grid-cols-1 gap-2 px-3 py-3 sm:grid-cols-[200px_1fr] sm:px-4">
                            <span className="text-sm font-semibold text-ink">{selectedSubtopic}</span>
                            <span className="text-sm leading-relaxed text-ink-muted">{selectedSubtopicHint}</span>
                          </div>
                        </div>
                      )}
                    </div>
                  )}

                  {setupStep === 4 && (
                    <>
                      <div className="mt-7 space-y-5">
                        <h4 className="text-2xl font-semibold italic tracking-tight text-ink md:text-3xl">Choose programming language</h4>
                        {selectedSubtopic && subtopicProgramOptions.length > 0 && (
                          <p className="text-sm leading-7 text-ink-soft">
                            Based on <span className="font-semibold text-ink">{selectedSubtopic}</span>, choose one or more programs/tools.
                          </p>
                        )}
                        <div className="grid gap-2.5 sm:grid-cols-2">
                          {languageChoices.map((language) => {
                            const selected = selectedLanguages.includes(language);
                            return (
                              <label
                                key={language}
                                className={`flex min-h-[2.5rem] cursor-pointer gap-2.5 rounded-sm border px-3 py-2 font-sans outline-none ring-offset-2 ring-offset-white transition-colors focus-within:ring-2 focus-within:ring-[#6366f1]/50 sm:items-center ${
                                  selected
                                    ? 'border-[#4f46e5] bg-[#0f172a]/[0.07] shadow-[inset_3px_0_0_0_#4f46e5]'
                                    : 'border-[#1e293b]/22 bg-parchment-50/85 hover:border-[#4f46e5]/42 hover:bg-[#0f172a]/[0.03]'
                                }`}
                              >
                                <input
                                  type="checkbox"
                                  name={`language-${language}`}
                                  value={language}
                                  checked={selected}
                                  onChange={(e) => {
                                    setSelectedLanguages((prev) =>
                                      e.target.checked
                                        ? prev.includes(language)
                                          ? prev
                                          : [...prev, language]
                                        : prev.filter((item) => item !== language),
                                    );
                                  }}
                                  className="sr-only"
                                />
                                <span
                                  className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md border-2 transition-colors sm:mt-0 ${
                                    selected
                                      ? 'border-parchment-800 bg-parchment-800 shadow-[0_0_0_2px_rgba(255,248,235,0.88)]'
                                      : 'border-parchment-500/60 bg-parchment-100'
                                  }`}
                                  aria-hidden
                                >
                                  {selected && (
                                    <svg className="h-2.5 w-2.5 text-white" viewBox="0 0 12 12" fill="none" aria-hidden>
                                      <path
                                        d="M2.5 6.5 L5 9 L9.5 3.5"
                                        stroke="currentColor"
                                        strokeWidth="1.8"
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                      />
                                    </svg>
                                  )}
                                </span>
                                <span className="min-w-0 flex-1 text-left text-sm font-semibold leading-snug text-ink">{language}</span>
                              </label>
                            );
                          })}
                        </div>
                      </div>
                      <div className="animate-flow-left-right mt-8 border-l-2 border-[#4f46e5]/40 pl-5 text-base leading-8 text-ink-muted">
                        <p>
                          Degrees don&apos;t prove skill - performance does.
                          <br />
                          We use AI-driven assessments to evaluate real abilities and issue blockchain-backed certifications you can
                          trust.
                        </p>
                        <p className="mt-3 text-lg font-bold text-stone-800">
                          Join a global network where your skills are tested, verified, and recognized.
                        </p>
                      </div>
                    </>
                  )}

                  {setupStep === 5 && (
                    <div className="mt-6 space-y-4">
                      <div>
                        <h4 className="text-2xl font-semibold italic tracking-tight text-ink md:text-3xl">
                          Review and enter examination room
                        </h4>
                        <p className="mt-1.5 text-sm leading-6 text-ink-soft">
                          Confirm your selected setup and review the exam policy before starting questions.
                        </p>
                      </div>

                      <section className="rounded-md border border-[#1e293b]/35 bg-[#0f172a]/[0.03] p-3">
                        <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">Selected elements</p>
                        <div className="mt-2 grid gap-1.5 sm:grid-cols-2">
                          <div className="rounded-sm border border-[#1e293b]/25 bg-parchment-50 px-3 py-1.5">
                            <p className="text-[11px] font-semibold uppercase tracking-wide text-ink-soft">Difficulty</p>
                            <p className="mt-0.5 text-sm font-semibold text-ink">
                              {DIFFICULTY_OPTIONS.find((opt) => opt.value === difficulty)?.label ?? difficulty}
                            </p>
                          </div>
                          <div className="rounded-sm border border-[#1e293b]/25 bg-parchment-50 px-3 py-1.5">
                            <p className="text-[11px] font-semibold uppercase tracking-wide text-ink-soft">Field</p>
                            <p className="mt-0.5 text-sm font-semibold text-ink">{selectedFieldConfig?.label ?? '-'}</p>
                          </div>
                          <div className="rounded-sm border border-[#1e293b]/25 bg-parchment-50 px-3 py-1.5">
                            <p className="text-[11px] font-semibold uppercase tracking-wide text-ink-soft">Subtopic</p>
                            <p className="mt-0.5 text-sm font-semibold text-ink">{selectedSubtopic ?? '-'}</p>
                          </div>
                          <div className="rounded-sm border border-[#1e293b]/25 bg-parchment-50 px-3 py-1.5">
                            <p className="text-[11px] font-semibold uppercase tracking-wide text-ink-soft">Languages</p>
                            <p className="mt-0.5 text-sm font-semibold text-ink">
                              {selectedLanguages.length > 0 ? selectedLanguages.join(', ') : '-'}
                            </p>
                          </div>
                          <div className="rounded-sm border border-[#1e293b]/25 bg-parchment-50 px-3 py-1.5 sm:col-span-2">
                            <p className="text-[11px] font-semibold uppercase tracking-wide text-ink-soft">Session length</p>
                            <p className="mt-0.5 text-sm font-semibold text-ink">
                              {formatSessionDuration(SESSION_DURATION_MINUTES)}
                            </p>
                          </div>
                        </div>
                      </section>

                      {stripePaymentRequired ? (
                        <section className="rounded-md border border-[#1e293b]/45 bg-[#0f172a]/[0.04] p-4">
                          <h5 className="text-lg font-semibold italic text-ink">Exam fee</h5>
                          <p className="mt-2 text-sm leading-relaxed text-ink-muted">
                            Each attempt costs <strong className="text-ink">{examFeeLabel}</strong> (per track on the
                            dashboard). Payment is processed securely by Stripe.
                          </p>
                          {paymentStatusLoading ? (
                            <p className="mt-3 text-sm text-ink-soft">Checking payment status…</p>
                          ) : hasExamPaymentCredit ? (
                            <p className="mt-3 rounded-md border border-emerald-300/70 bg-emerald-50/90 px-3 py-2 text-sm font-medium text-emerald-900">
                              Payment confirmed — you can enter the exam room.
                            </p>
                          ) : (
                            <div className="mt-3 space-y-2">
                              <p className="text-sm text-amber-900">Pay before starting your timed session.</p>
                              <button
                                type="button"
                                onClick={() => {
                                  setErr(null);
                                  void beginCheckout(selectedField, setErr);
                                }}
                                disabled={paymentBusy}
                                className="inline-flex rounded-md border border-parchment-800 bg-parchment-800 px-4 py-2 text-sm font-semibold text-parchment-50 transition hover:bg-parchment-900 disabled:opacity-60"
                              >
                                {paymentBusy ? 'Redirecting to Stripe…' : `Pay ${examFeeLabel} with Stripe`}
                              </button>
                            </div>
                          )}
                        </section>
                      ) : null}

                      <section className="rounded-md border border-[#1e293b]/35 bg-transparent p-3">
                        <h5 className="text-lg font-semibold italic text-ink">Examination briefing</h5>
                        <ul className="mt-2 list-inside list-disc space-y-1 text-sm leading-relaxed text-ink-muted marker:text-[#4f46e5]">
                          <li>
                            <strong className="font-semibold text-ink">Allocated time:</strong>{' '}
                            {formatSessionDuration(SESSION_DURATION_MINUTES)} for the full assessment (all five parts).
                          </li>
                          <li>
                            <strong className="font-semibold text-ink">Grading regulations:</strong> MCQ is auto-scored and written/practical/interview parts are AI-evaluated with rubric checks.
                          </li>
                          <li>
                            <strong className="font-semibold text-ink">Rules to observe:</strong> complete independently, avoid tab switching, and keep the session stable until grading is complete.
                          </li>
                          <li>
                            <strong className="font-semibold text-ink">Examination method:</strong> 5 parts - MCQ, written answers, mistake correction, practical tasks, and AI interview.
                          </li>
                          <li>
                            <strong className="font-semibold text-ink">Session capture:</strong> After you click Enter exam room, your browser will prompt you to share this tab or your screen; recording then runs automatically for your attempt.
                          </li>
                        </ul>
                      </section>
                    </div>
                  )}

                </div>
              </div>
            </div>
          </div>
            )}
          {err && (
            <p className="mx-auto mb-2 max-w-full rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              {err}
            </p>
          )}
          </div>

          <div className="sticky bottom-0 z-20 mt-auto shrink-0 -mx-4 border-t border-stone-400/40 bg-parchment-50/95 px-4 py-4 shadow-[0_-8px_24px_-12px_rgba(28,25,23,0.1)] backdrop-blur-md sm:-mx-6 sm:px-6">
            {setupPhase === 'intro' ? (
              <div className="flex w-full flex-col items-stretch gap-3 sm:flex-row sm:items-center sm:justify-end">
                <button
                  type="button"
                  disabled={!allIntroRulesAcknowledged}
                  onClick={() => {
                    if (!allIntroRulesAcknowledged) return;
                    setErr(null);
                    setSetupPhase('wizard');
                    setSetupStep(1);
                  }}
                  title={
                    allIntroRulesAcknowledged ? undefined : 'Check the box next to each rule in the Rules section to continue.'
                  }
                  className="inline-flex w-full items-center justify-center rounded-lg bg-parchment-800 px-6 py-3 text-sm font-semibold text-white transition hover:bg-parchment-900 disabled:cursor-not-allowed disabled:opacity-45 sm:w-auto"
                >
                  Continue to setup
                </button>
              </div>
            ) : (
              <div className="flex items-center justify-between gap-3">
                <button
                  type="button"
                  className="rounded-md border border-[#1e293b]/45 bg-transparent px-4 py-2 text-sm font-semibold text-ink transition hover:bg-[#0f172a]/[0.06]"
                  onClick={() => {
                    if (setupStep === 1) {
                      setErr(null);
                      setSetupPhase('intro');
                      return;
                    }
                    setSetupStep((prev) => (prev > 1 ? (prev - 1) as SetupStep : prev));
                  }}
                >
                  {setupStep === 1 ? '← Details & rules' : 'Back'}
                </button>
                <div className="flex items-center gap-2">
                  {SETUP_STEPS.map((step) => (
                    <span
                      key={step.id}
                      className={`h-2.5 w-2.5 rounded-full ${setupStep === step.id ? 'bg-[#4f46e5]' : 'bg-slate-300'}`}
                    />
                  ))}
                </div>
                {setupStep < 5 ? (
                  <button
                    type="button"
                    className="rounded-md bg-parchment-800 px-5 py-2 text-sm font-semibold text-white transition hover:bg-parchment-900"
                    onClick={() => {
                      if (setupStep === 2 && !selectedField) {
                        setErr('Please choose a field.');
                        return;
                      }
                      if (setupStep === 3 && selectedTopics.length === 0) {
                        setErr('Please choose a subtopic.');
                        return;
                      }
                      if (setupStep === 4 && selectedLanguages.length === 0) {
                        setErr('Please choose at least one language.');
                        return;
                      }
                      setErr(null);
                      setSetupStep((prev) => (prev < 5 ? (prev + 1) as SetupStep : prev));
                    }}
                  >
                    Continue
                  </button>
                ) : (
                  <button
                    type="button"
                    disabled={
                      stripePaymentRequired &&
                      (paymentStatusLoading || !hasExamPaymentCredit)
                    }
                    onClick={() => {
                      void (async () => {
                        setErr(null);
                        await sessionRecording.startRecording();
                        await start(undefined, { preserveActiveRecording: true });
                      })();
                    }}
                    className="rounded-md bg-parchment-800 px-5 py-2 text-sm font-semibold text-white transition hover:bg-parchment-900 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Enter exam room
                  </button>
                )}
              </div>
            )}
          </div>
        </div>

  );
}
